classdef XippmexStimulator < stim.StimulationInterface
    properties
        isInitialized = false
        mode = "TCP"
        address = '192.168.43.130'

        

        
        stimulationChannels = []%available stimulation channels of connected front-ends
        selectedChannels = []
        gndRefChannel = [];
        %%stimulationParameters
        stimulationCommand = [] %stimseq command generated by stim.generateSpatiotemporalPattern
        channelMap = []
        applyMap = false



        CC = 30e3 %clock cycle of stimulation processor (30kHz)
        ampResVal = [] % amplitude step resolution (uA/step)
        ampRes = [] % index of ampliduteResVal from ampResValList
        
        ampResValList = [10 20 50 100 200]
        ampResList = [1 2 3 4 5]

        
    end

    properties (Access = private)
        defaultStimulationParameters = struct("anode", 16, "cathode", 1, ...
                "sequential", false, "frequency", 50,"duration", 200, ...
                "amplitude", 200, "train_length", 2, "step", 100)

        stimTimer
    end


    methods

        function obj = XippmexStimulator(opts)

            arguments
                opts.channelMap dictionary %dictionary where keys correspond to channels labels of leads and values correspond to channels of ripple
            end

            obj.stimulationParameters = obj.defaultStimulationParameters;

            if isfield(opts, "channelMap")
               obj.channelMap = opts.channelMap;
               obj.applyMap = true;
            end
            
            %obj.stimulationCommand = stim.generateSpatiotemporalPattern(obj.defaultStimulationParameters);
            
            obj.stimTimer = timer('StartDelay', obj.stimulationParameters.train_length, ...
                'TimerFcn', @(~,~)obj.handleStimulusDelivered, ...
                'ExecutionMode','singleShot', 'Name', 'Stim Timer');


        end

        function initialize(obj, opts)
            arguments
                obj stim.XippmexStimulator
                opts.mode
                opts.address
            end

            % check if already initialized
            if obj.isInitialized
                obj.StatusMessage = "Stimulator already initialized.";
                return;
            end
            
            % set optional inputs
            if isfield(opts, "mode")
                obj.mode = opts.mode;
            end
            if isfield(opts, "address")
                obj.address = opts.address;
            end
            
            % enable xippmex 
            switch obj.mode
                case "TCP"
                    status = xippmex('tcp');
                otherwise
                    status = xippmex;
            end
            
            % return if initialization failed
            if status ~= 1
                obj.StatusMessage = "Xippmex did not initialize.";
                notify(obj, "InitializationError")
                return;
            end

            % check for stimulation channels on headstage
            stimChans = xippmex('elec','stim');
            if isempty(stimChans)
                obj.StatusMessage = "Warning: No stimulation hardware detected.";
                notify(obj, "InitializationError")
                return;
            end
            
            

            obj.stimulationChannels = stimChans; 
            if obj.applyMap
                obj.selectedChannels = stimChans(ismember(stimChans, values(obj.channelMap)));
            else
                obj.selectedChannels = stimChans;
            end
            obj.isInitialized = true; 
            obj.StatusMessage = "Stimulator initialized successfully.";
            notify(obj, "InitializationSuccess")

            enableRecording(obj);
            updateAmplitudeResolution(obj, obj.stimulationParameters.step)

        end

        function connected = isConnected(obj)
            connected = obj.isInitialized;
        end

        function updateParameters(obj, parameters)
            if ~obj.isInitialized
                obj.StatusMessage = "Xippmex not initialized.";
                return;
            end
            % parameters = struct("vibration_level", 100)
            % parameters = struct("vibration_level", 100, "vibration_length", 2000)
            for field = string(fieldnames(parameters))'
                new_param = parameters.(field);
                if strcmp(field, 'anode') || strcmp(field, 'cathode') && obj.applyMap
                    obj.stimulationParameters.(field) = obj.channelMap(new_param);
                else
                    obj.stimulationParameters.(field) = new_param;
                end
            end
            obj.stimTimer.StartDelay = obj.stimulationParameters.train_length;
            obj.stimulationCommand = stim.generateSpatiotemporalPattern(obj.stimulationParameters);
            %obj.stimulationCommand;
            obj.StatusMessage = "Parameters updated.";
            %obj.StatusMessage = sprintf('Cathodes: %s', strjoin(string(obj.stimulationParameters.cathode), ', '));
            %obj.StatusMessage = sprintf('Anodes: %s', strjoin(string(obj.stimulationParameters.anode), ', '));

        end


        function deliverStimulus(obj)
            %% deliver stimuation at with current stimulation command
            if ~obj.isInitialized
                notify(obj, "StimulationError")
                obj.StatusMessage = "Xippmex not initialized.";
                return;
            end
            % disp('here')
            obj.StatusMessage = "Delivering stimulation...";
            for i = 1:length(obj.stimulationCommand)
                xippmex('stimseq', obj.stimulationCommand{i})
            end
            start(obj.stimTimer)

        end

        function stopStimulus(obj)
            if ~obj.isInitialized
                return;
            end
            writeline(obj.serObj, 'V0')
        end

        function cleanup(obj)
            if ~obj.isInitialized
                obj.StatusMessage = "Xippmex not initialized";
                return;
            end

            if xippmex('stim', 'enable') == 1
                xippmex('stim', 'enable', 0)
                pause(0.5)
            end
            xippmex('close')
            obj.isInitialized = false;
            obj.StatusMessage = "Xippmex closed.";

        end

        function delete(obj)
            
            cleanup(obj);
            if ~isempty(obj.stimTimer) && isvalid(obj.stimTimer)
                stop(obj.stimTimer)
                delete(obj.stimTimer)
                obj.stimTimer = [];
            end
        end

        function attatchListener(obj)
            addlistener(obj, "StatusMessage", "PostSet", @(src, event)stim.XippmexStimulator.displayStatusMessage(@fprintf, src, event));
        end


        function updateAmplitudeResolution(obj, new_res_val)
            if ~obj.isInitialized
                obj.StatusMessage = "Xippmex not initialized.";
                return;
            end
            if new_res_val == obj.ampResVal
                obj.StatusMessage = "Amplitude resolution already applied.";
                return;
            end
            new_res = obj.ampResList(ismember(obj.ampResValList, new_res_val));
            if isempty(new_res) || ~isscalar(new_res)
                obj.StatusMessage = "Invalid amplitude resolution.";
                return;
            end
            

            if xippmex('stim', 'enable') == 1
                xippmex('stim', 'enable', 0)
                pause(0.5)
            end

            
            xippmex('stim', 'res', obj.selectedChannels, new_res)
            pause(0.2)
            xippmex('stim', 'enable', 1)
            pause(0.5)

            obj.ampRes = new_res;
            obj.ampResVal = new_res_val;
            obj.stimulationParameters.step = new_res_val;
            obj.stimulationCommand = stim.generateSpatiotemporalPattern(obj.stimulationParameters);
            obj.StatusMessage = "Amplitude resolution set to: " + obj.ampResVal + "uA";


        end


        function setGndRef(obj, chan)
            if ~obj.isInitialized
                obj.StatusMessage = "Xippmex not initialized.";
                return;
            end
            if obj.applyMap
                chan = obj.channelMap(chan);
            end
            xippmex('ground', chan, 1);
            xippmex('reference', chan, 1);
            obj.gndRefChannel = chan;
            obj.StatusMessage = "Ground/reference channel set: " + chan;
        end

        function removeGndRef(obj)
            if ~obj.isInitialized
                obj.StatusMessage = "Xippmex not initialized.";
                return;
            end
            if isempty(obj.gndRefChannel)
                obj.StatusMessage = "No ground/reference set";
                return;
            end
            xippmex('ground', obj.gndRefChannel, 0);
            xippmex('reference', obj.gndRefChannel, 0);
            
            obj.StatusMessage = "Ground/reference removed from channel " + obj.gndRefChannel;
            obj.gndRefChannel = [];
        end

        


    end

    methods (Access = private)
        
        function enableRecording(obj)
            if ~obj.isInitialized
                return;
            end
            if ~strcmp(obj.mode, "TCP")
                return;
            end
            % set operator ID to enable recording through xippmex
            operator_val = xippmex('addoper', obj.address);
            % returns the address as uint32 -> 8x4 = 32, 8bit for each
            % octet in the ip address. Convert back to char by
            % typecasting to uint8 and comparing to the input address
            operator_address = char(strjoin(string(typecast(operator_val, 'uint8')), '.'));
            if ~strcmp(operator_address, obj.address)
                obj.StatusMessage = "Warning: Operator ID issue.";
            else
                obj.StatusMessage = "Operator ID added at: " + operator_address;
            end
            

        end

        function handleStimulusDelivered(obj)
            notify(obj, "StimulusDelivered")
            obj.StatusMessage = "Stimulation complete.";
        end


    end

    methods (Static)

        function displayStatusMessage(displayFcn, src, event)
            d = string(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss'));
            msg = event.AffectedObject.(src.Name);
            prefix = sprintf('[XippmexStimulator %s]', d);
            displayFcn(sprintf('%s %s\n', prefix, msg))
        end
    end


end