classdef XippmexStimulatorSim < stim.StimulationInterface
    %%
    properties
        isInitialized = false
        mode = "TCP"
        address = '192.168.43.130'

        

        
        stimulationChannels = []%available stimulation channels of connected front-ends
        selectedChannels = []
        gndRefChannel = [];
        gndChannel = [];
        refChannel = [];

        %%stimulationParameters
        stimulationCommand = [] %stimseq command generated by stim.generateSpatiotemporalPattern
        channelMap = []
        applyMap = false



        %CC = 30e3 %clock cycle of stimulation processor (30kHz)
        ampResVal = [] % amplitude step resolution (uA/step)
        ampRes = [] % index of ampliduteResVal from ampResValList
        maxSteps = []
        ampMax = []
        ampMin = []



        ampResList = [1 2 3 4 5]
        ampResValList = [1 2 5 10 20]
        maxStepsList = [100,100,100,100,75]

        fastSettle = true
        
        parameterDisplayNames = ["Anode(s)"; "Cathode(s)"; "Sequential Pattern"; ...
            "Frequency (Hz)"; "Pulse-width (us)"; "Amplitude"; "Train Length (s)"; ...
            "Step"; "Cathode Amplitude"; "Anode Amplitude"];

        
    end

    properties (Access = private)
        defaultStimulationParameters = struct("anode", 16, "cathode", 1, ...
                "sequential", false, "frequency", 50,"duration", 200, ...
                "amplitude", 200, "train_length", 2, "step", 2, ...
                "amplitude_cathode", 200, "amplitude_anode", 200);

        % parameterDisplayNames = ["Anode(s)"; "Cathode(s)"; "Sequential Pattern"; ...
        %     "Frequency (Hz)"; "Pulse-width (us)"; "Amplitude"; "Train Length (s)"; ...
        %     "Step"; "Cathode Amplitude"; "Anode Amplitude"];

        parameterNameMap = []

        clearCMD = struct("elec", [], "period", [], "repeats", [], "action", [], "seq", []);
        
        stimTimer

        recordingEnabled = false
        isRecording = false
        operatorAddress = []
    end

    events
        AmplitudeCorrected
        AmplitudeDistributed
    end


    methods

        function obj = XippmexStimulatorSim(opts)
            %% constructor
            arguments
                opts.channelMap dictionary %dictionary where keys correspond to channels labels of leads and values correspond to channels of ripple
                opts.frontEndType = "Pico"
            end

            obj.stimulationParameters = obj.defaultStimulationParameters;
            obj.parameterNameMap = dictionary(string(fieldnames(obj.stimulationParameters)), obj.parameterDisplayNames);

            if isfield(opts, "channelMap")
               obj.channelMap = opts.channelMap;
               obj.applyMap = true;
            end
            if isfield(opts, "frontEndType")
                switch opts.frontEndType
                    case "Macro"
                        obj.ampResValList = stim.constants.AMPRESVALS_MACRO;
                        obj.maxStepsList = stim.constants.MAXSTEPS_MACRO;

                    case "Pico"
                        obj.ampResValList = stim.constants.AMPRESVALS_PICO;
                        obj.maxStepsList = stim.constants.MAXSTEPS_PICO;

                end
            end
            
            %obj.stimulationCommand = stim.generateSpatiotemporalPattern(obj.defaultStimulationParameters);
            
            % obj.stimTimer = timer('StartDelay', obj.stimulationParameters.train_length, ...
            %     'TimerFcn', @(~,~)obj.handleStimulusDelivered, ...
            %     'ExecutionMode','singleShot', 'Name', 'Stim Timer');


        end

        function initialize(obj, opts)
            %% initializes xippmex connection
            arguments
                obj stim.XippmexStimulatorSim
                opts.mode
                opts.address
            end

            % check if already initialized
            if obj.isInitialized
                obj.StatusMessage = "Stimulator already initialized.";
                return;
            end
            
            % set optional inputs
            if isfield(opts, "mode")
                obj.mode = opts.mode;
            end
            if isfield(opts, "address")
                obj.address = opts.address;
            end
            
            % enable xippmex 
            switch obj.mode
                case "TCP"
                    status = 1;%xippmex('tcp');
                otherwise
                    status = 1;%xippmex;
            end
            
            % return if initialization failed
            if status ~= 1
                obj.StatusMessage = "Xippmex did not initialize.";
                notify(obj, "InitializationError")
                return;
            end

            % check for stimulation channels on headstage
            stimChans = 1:32;%xippmex('elec','stim');
            if isempty(stimChans)
                obj.StatusMessage = "Warning: No stimulation hardware detected.";
                notify(obj, "InitializationError")
                return;
            end
            
            
            
            obj.stimulationChannels = stimChans; 
            if obj.applyMap
                obj.selectedChannels = stimChans(ismember(stimChans, values(obj.channelMap)));
            else
                obj.selectedChannels = stimChans;
            end
            obj.stimTimer = timer('StartDelay', obj.stimulationParameters.train_length, ...
                'TimerFcn', @(~,~)obj.handleStimulusDelivered, ...
                'ExecutionMode','singleShot', 'Name', 'Stim Timer');
            obj.isInitialized = true; 
            obj.StatusMessage = "Stimulator initialized successfully.";
            notify(obj, "InitializationSuccess")
            
            generateClearCmd(obj);
            enableRecording(obj);
            updateAmplitudeResolution(obj, obj.stimulationParameters.step)

        end

        function connected = isConnected(obj)
            connected = obj.isInitialized;
        end

        function updateParameters(obj, parameters)
            if ~obj.isInitialized
                obj.StatusMessage = "Xippmex not initialized.";
                return;
            end
            % parameters = struct("vibration_level", 100)
            % parameters = struct("vibration_level", 100, "vibration_length", 2000)
            for field = string(fieldnames(parameters))'
                new_param = parameters.(field);
                if strcmp(field, 'anode') || strcmp(field, 'cathode') && obj.applyMap
                    obj.stimulationParameters.(field) = obj.channelMap(new_param);
                else
                    obj.stimulationParameters.(field) = new_param;
                end
                if ~strcmp(field, 'amplitude')
                    obj.StatusMessage = obj.parameterNameMap(field) + " set to: " + num2str(new_param);
                end
            end
            obj.stimTimer.StartDelay = obj.stimulationParameters.train_length;
            %obj.stimulationCommand = stim.generateSpatiotemporalPattern(obj.stimulationParameters);
            [obj.stimulationCommand, amp_info] = stim.generateStimulationCommand(obj.stimulationParameters);
            %obj.stimulationCommand;
            if ~amp_info.validInput
                obj.stimulationParameters.amplitude = amp_info.ampValid;
                
                %obj.stimulationParameters.amplitude_anode] = deal(obj.stimulationParameters.amplitude);
                obj.StatusMessage = sprintf('Amplitude corrected to %d uA', amp_info.ampValid);
                notify(obj, "AmplitudeCorrected");
            end
            if ~obj.stimulationParameters.sequential
                obj.StatusMessage = sprintf('Cathode amplitude set to %d uA', amp_info.ampCathode);
                obj.StatusMessage = sprintf('Anode amplitude set to %d uA', amp_info.ampAnode);
                obj.stimulationParameters.amplitude_cathode = amp_info.ampCathode;
                obj.stimulationParameters.amplitude_anode = amp_info.ampAnode;
                notify(obj, "AmplitudeDistributed");
                
            else
                [obj.stimulationParameters.amplitude_cathode, obj.stimulationParameters.amplitude_anode] = deal(obj.stimulationParameters.amplitude);
            end
            obj.StatusMessage = "Parameters updated.";
            %obj.StatusMessage = sprintf('Cathodes: %s', strjoin(string(obj.stimulationParameters.cathode), ', '));
            %obj.StatusMessage = sprintf('Anodes: %s', strjoin(string(obj.stimulationParameters.anode), ', '));

        end

        function modulateParameters(obj, params)


        end


        function deliverStimulus(obj)
            %% deliver stimuation at with current stimulation command
            if ~obj.isInitialized
                notify(obj, "StimulationError")
                obj.StatusMessage = "Xippmex not initialized.";
                return;
            end
            % disp('here')
            obj.StatusMessage = "Delivering stimulation...";
            for i = 1:length(obj.stimulationCommand)
                %xippmex('stimseq', obj.stimulationCommand{i})
                obj.StatusMessage = "Queue" + num2str(i);
            end
            start(obj.stimTimer)

        end



        function stopStimulus(obj)
            if ~obj.isInitialized
                return;
            end
            obj.StatusMessage = "Stimulation Stopped.";
            %writeline(obj.serObj, 'V0')
        end

        function deliverCMD(obj, cmd_cell)
        %% USE CAREFULLY
        % delivers stimulation stimseq command(s) in cmd_cell directly
        % only checks if XippmexStimulator object is initialized, not if
        % the contents in cmd_cell contain valid stimseq commands
        % Only has a try-catch statement that will trigger on stimseq errors
            if ~obj.isInitialized
                notify(obj, "StimulationError")
                obj.StatusMessage = "Xippmex not initialized.";
                return;
            end
            obj.StatusMessage = "Delivering stimulation...";
            try
                for i = 1:length(cmd_cell)
                    %xippmex('stimseq', cmd_cell{i})
                    obj.StatusMessage = "Queue" + num2str(i);
                end
                start(obj.stimTimer)

            catch ME
                notify(obj, "StimulationError")
                obj.StatusMessage = ME.message;
                assignin("base", "ME", ME)
                assignin("base", "cmd_cell", cmd_cell)
            end

        end

        function generateClearCmd(obj)
            if ~obj.isInitialized
                return;
            end
            for i = 1:length(obj.selectedChannels)
                obj.clearCMD(i).elec = obj.selectedChannels(i);
                obj.clearCMD(i).period = 20;
                obj.clearCMD(i).repeats = 1;
                obj.clearCMD(i).action = 'immed';
                obj.clearCMD(i).seq = struct('length', 3, 'ampl', 0, 'pol', 0, ...
                    'fs', 0, 'enable', 0, 'delay', 0, 'ampSelect', 0);
            end


        end

        function cleanup(obj)
            if ~obj.isInitialized
                obj.StatusMessage = "Xippmex not initialized";
                return;
            end

            % if xippmex('stim', 'enable') == 1
            %     xippmex('stim', 'enable', 0)
            %     pause(0.5)
            % end
            % xippmex('close')
            obj.isInitialized = false;
            obj.StatusMessage = "Xippmex closed.";

        end

        function delete(obj)
            
            cleanup(obj);
            if ~isempty(obj.stimTimer) && isvalid(obj.stimTimer)
                stop(obj.stimTimer)
                delete(obj.stimTimer)
                obj.stimTimer = [];
            end
        end

        function attatchListener(obj)
            addlistener(obj, "StatusMessage", "PostSet", @(src, event)stim.XippmexStimulatorSim.displayStatusMessage(@fprintf, src, event));
        end


        function updateAmplitudeResolution(obj, new_res_val)
            if ~obj.isInitialized
                obj.StatusMessage = "Xippmex not initialized.";
                return;
            end
            if new_res_val == obj.ampResVal
                obj.StatusMessage = "Amplitude resolution already applied.";
                return;
            end
            new_res = obj.ampResList(ismember(obj.ampResValList, new_res_val));
            if isempty(new_res) || ~isscalar(new_res)
                obj.StatusMessage = "Invalid amplitude resolution.";
                return;
            end
            

            % if xippmex('stim', 'enable') == 1
            %     xippmex('stim', 'enable', 0)
            %     pause(0.5)
            % end

            
            % xippmex('stim', 'res', obj.selectedChannels, new_res)
            % pause(0.2)
            % xippmex('stim', 'enable', 1)
            % pause(0.5)

            obj.ampRes = new_res;
            obj.ampResVal = new_res_val;
            obj.maxSteps = obj.maxStepsList(new_res);
            obj.ampMax = obj.ampResVal * obj.maxSteps;
            obj.ampMin = obj.ampResVal;
            obj.stimulationParameters.step = new_res_val;
            %obj.stimulationCommand = stim.generateSpatiotemporalPattern(obj.stimulationParameters);
            [obj.stimulationCommand, amp_info] = stim.generateStimulationCommand(obj.stimulationParameters, "fastSettle", obj.fastSettle);
            %obj.stimulationCommand;
            if ~amp_info.validInput
                obj.stimulationParameters.amplitude = amp_info.ampValid;
                
                %obj.stimulationParameters.amplitude_anode] = deal(obj.stimulationParameters.amplitude);
                obj.StatusMessage = sprintf('Amplitude corrected to %d uA', amp_info.ampValid);
                notify(obj, "AmplitudeCorrected");
            end
            if ~obj.stimulationParameters.sequential
                obj.StatusMessage = sprintf('Cathode amplitude set to %d uA', amp_info.ampCathode);
                obj.StatusMessage = sprintf('Anode amplitude set to %d uA', amp_info.ampAnode);
                obj.stimulationParameters.amplitude_cathode = amp_info.ampCathode;
                obj.stimulationParameters.amplitude_anode = amp_info.ampAnode;
                notify(obj, "AmplitudeDistributed");
                
            else
                [obj.stimulationParameters.amplitude_cathode, obj.stimulationParameters.amplitude_anode] = deal(obj.stimulationParameters.amplitude);
            end
            obj.StatusMessage = "Parameters updated.";
            obj.StatusMessage = "Amplitude resolution set to: " + obj.ampResVal + "uA";


        end


        function setGndRef(obj, chan)
            if ~obj.isInitialized
                obj.StatusMessage = "Xippmex not initialized.";
                return;
            end
            if obj.applyMap
                chan = obj.channelMap(chan);
            end
            %xippmex('ground', chan, 1);
            %xippmex('reference', chan, 1);
            obj.gndRefChannel = chan;
            obj.StatusMessage = "Ground/reference channel set: " + chan;
        end

        function removeGndRef(obj)
            if ~obj.isInitialized
                obj.StatusMessage = "Xippmex not initialized.";
                return;
            end
            if isempty(obj.gndRefChannel)
                obj.StatusMessage = "No ground/reference set";
                return;
            end
            %xippmex('ground', obj.gndRefChannel, 0);
            %xippmex('reference', obj.gndRefChannel, 0);
            
            obj.StatusMessage = "Ground/reference removed from channel " + obj.gndRefChannel;
            obj.gndRefChannel = [];
        end

        function setGnd(obj, chan)
            %% set selected channel 'chan' to ground only
            if ~obj.isInitialized
                obj.StatusMessage = "Xippmex not initialized.";
                return;
            end
            if ~obj.isInitialized
                obj.StatusMessage = "Xippmex not initialized.";
                return;
            end
            if obj.applyMap
                chan = obj.channelMap(chan);
            end

            %xippmex('ground', chan, 1);
            obj.gndChannel = chan;
            obj.StatusMessage = "Ground channel set: " + chan;
        end

        function removeGnd(obj)
            %% remove previously selected channel from ground only
            if ~obj.isInitialized
                obj.StatusMessage = "Xippmex not initialized.";
                return;
            end
            if isempty(obj.gndChannel)
                obj.StatusMessage = "No ground set";
                return;
            end
            %xippmex('ground', obj.gndChannel, 0);            
            obj.StatusMessage = "Ground removed from channel " + obj.gndChannel;
            obj.gndChannel = [];
        end

        function setRef(obj, chan)
            %% set selected channel 'chan' to reference only
            if ~obj.isInitialized
                obj.StatusMessage = "Xippmex not initialized.";
                return;
            end
            if ~obj.isInitialized
                obj.StatusMessage = "Xippmex not initialized.";
                return;
            end
            if obj.applyMap
                chan = obj.channelMap(chan);
            end

            %xippmex('reference', chan, 1);
            obj.refChannel = chan;
            obj.StatusMessage = "Reference channel set: " + chan;
        end

        function removeRef(obj)
            %% remove previously selected channel from ground only
            if ~obj.isInitialized
                obj.StatusMessage = "Xippmex not initialized.";
                return;
            end
            if isempty(obj.refChannel)
                obj.StatusMessage = "No reference set";
                return;
            end
            %xippmex('reference', obj.refChannel, 0);            
            obj.StatusMessage = "Ground removed from channel " + obj.refChannel;
            obj.refChannel = [];
        end

        function setRecordingParameters(obj, save_path)
            %% set recording parameters
            % currently just to specify save path. 
            % also resets autoincriment 
            if ~obj.isInitialized
                return;
            end
            if ~strcmp(obj.mode, "TCP")
                return;
            end
            if ~obj.recordingEnabled
                return;
            end
            disp('here')
            %xippmex('trial', obj.operatorAddress, save_path, 0, 0);
        end

        function startRecording(obj, save_file_path)
            if ~obj.recordingEnabled
                return;
            end
            
            %xippmex('trial', obj.operatorAddress, save_file_path, 0, 0, 1);
            %xippmex('trial', 'recording');
            obj.isRecording = true;
            obj.StatusMessage = "Recording started: " + string(save_file_path); 


        end

        function stopRecording(obj)
            if ~obj.isRecording
                return;
            end
            
            %xippmex('trial', obj.operatorAddress, 'stopped');
            try 
                %xippmex('trial', 'stopped');
                obj.StatusMessage = "Recording stopped.";
                obj.isRecording = false;
            catch ME
                if contains(ME.message, 'A file with this name already exists')
                    % when auto-incriment is set to off, stopping the
                    % recording with "xippmex('trial', 'stopped') does stop
                    % the recording but immediately throws an error that
                    % the name of the file already exists. Can't figure out
                    % a way to not have this happen. Because it does stop
                    % the recording, I'm just catching the error message
                    % and having it continue as if nothing happened.
                    obj.StatusMessage = "Recording stopped.";
                    obj.isRecording = false;
                else
                    obj.StatusMessage = ME.message;
                    
                end

            end

        end

        


    end

    methods (Access = private)
        
        function enableRecording(obj)
            if ~obj.isInitialized
                return;
            end
            if ~strcmp(obj.mode, "TCP")
                return;
            end
            % set operator ID to enable recording through xippmex
            % operator_val = xippmex('addoper', obj.address);
            % returns the address as uint32 -> 8x4 = 32, 8bit for each
            % octet in the ip address. Convert back to char by
            % typecasting to uint8 and comparing to the input address
            % operator_address = char(strjoin(string(typecast(operator_val, 'uint8')), '.'));
            % if ~strcmp(operator_address, obj.address)
            %     obj.StatusMessage = "Warning: Operator ID issue.";
            % else
            %     obj.StatusMessage = "Operator ID added at: " + operator_address;
            % end
            obj.StatusMessage = "Operator ID added at: " + obj.address;

        end

        function handleStimulusDelivered(obj)
            notify(obj, "StimulusDelivered")
            obj.StatusMessage = "Stimulation complete.";
        end


    end

    methods (Static)

        function displayStatusMessage(displayFcn, src, event)
            d = string(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss'));
            msg = event.AffectedObject.(src.Name);
            prefix = sprintf('[XippmexStimulator %s]', d);
            displayFcn(sprintf('%s %s\n', prefix, msg))
        end
    end


end